export const sampleData = {
    projects: [
        {
            id: 1,
            name: 'Work',
            todos: [
                {
                    id: 11,
                    title: 'Meeting with clients',
                    project: 'Work',
                    description: 'Discuss project requirements',
                    dueDate: '2024-03-25',
                    priority: 'high',
                    completed: true,
                },
                {
                    id: 22,
                    title: 'Prepare presentation',
                    project: 'Work',
                    description: 'Create slides for the upcoming presentation',
                    dueDate: '2024-03-28',
                    priority: 'medium',
                    completed: false,
                },
            ],
        },
        {
            id: 2,
            name: 'Personal',
            todos: [
                {
                    id: 33,
                    title: 'Go grocery shopping',
                    project: 'Personal',
                    description: 'Buy fruits, vegetables, and milk',
                    dueDate: '2024-03-15',
                    priority: 'high',
                    completed: true,
                },
                {
                    id: 44,
                    title: 'Gym workout',
                    project: 'Personal',
                    description: 'Cardio and weight training session',
                    dueDate: '2024-03-15',
                    priority: 'low',
                    completed: false,
                },
            ],
        },
        {
            id: 3,
            name: 'Home Improvement',
            todos: [
                {
                    id: 55,
                    title: 'Paint living room walls',
                    project: 'Home Improvement',
                    description: 'Choose paint color and buy supplies',
                    dueDate: '2024-03-16',
                    priority: 'medium',
                    completed: true,
                },
                {
                    id: 66,
                    title: 'Fix leaking faucet',
                    project: 'Home Improvement',
                    description: 'Call plumber to fix the kitchen faucet',
                    dueDate: '2024-03-17',
                    priority: 'high',
                    completed: true,
                },
            ],
        },
        {
            id: 4,
            name: 'Fitness Goals',
            todos: [
                {
                    id: 77,
                    title: 'Run 5 miles',
                    project: 'Fitness Goals',
                    description: 'Run in the park early morning',
                    dueDate: '2024-03-15',
                    priority: 'high',
                    completed: false,
                },
                {
                    id: 88,
                    title: 'Try new yoga class',
                    project: 'Fitness Goals',
                    description: 'Attend the evening yoga class at the gym',
                    dueDate: '2024-03-16',
                    priority: 'medium',
                    completed: false,
                },
            ],
        },
        {
            id: 5,
            name: 'Vacation Planning',
            todos: [
                {
                    id: 99,
                    title: 'Book flight tickets',
                    project: 'Vacation Planning',
                    description: 'Search for best deals and book tickets',
                    dueDate: '2024-03-25',
                    priority: 'high',
                    completed: false,
                },
                {
                    id: 1010,
                    title: 'Research accommodation options',
                    project: 'Vacation Planning',
                    description: 'Find suitable hotels or Airbnb',
                    dueDate: '2024-03-26',
                    priority: 'medium',
                    completed: false,
                },
            ],
        },
    ],
};
